package server;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import server.userDAO.UserDAO;

import client.ClientController;

public class ServerGUI extends javax.swing.JFrame implements ActionListener {

   
	  // Variables declaration - do not modify
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NumberButton;
    private javax.swing.JTextField clientNumberField;
    private javax.swing.JComboBox conectedUsers;
    private javax.swing.JLabel controlLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton disconectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField maxNumber;
    private javax.swing.JButton modifyBotton;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nikField;
    private javax.swing.JLabel numberConectLabel;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel statusBar;
    TableModel model = null;
    ServerController controller=null;
    UserDAO dao= new UserDAO();
    // End of variables declaration
	
	
	
	/** Creates new form ServerGUI */
    public ServerGUI(ServerController serverController) {
        super();
        initComponents();
        controller = serverController;
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
            	

            }
    });
    
}
    
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        controlLabel = new javax.swing.JLabel();
        clientNumberField = new javax.swing.JTextField();
        numberConectLabel = new javax.swing.JLabel();
        maxNumber = new javax.swing.JTextField();
        NumberButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        conectedUsers = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        disconectButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        modifyBotton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nikField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        statusBar = new javax.swing.JLabel();
       
        
        ExitButton.addActionListener(this);
        NumberButton.addActionListener(this);
        disconectButton.addActionListener(this);
        newButton.addActionListener(this);
        modifyBotton.addActionListener(this);
        deleteButton.addActionListener(this);
        
        conectedUsers.addActionListener(this);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlLabel.setText("Total number of connected clients:");

        numberConectLabel.setText("Set maximun number of conections:");

        NumberButton.setText("Add");
       

        jLabel1.setText("Connected Ussers");

        conectedUsers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "", "", "" }));
       
        model=(new DefaultTableModel(
			        				new String [][] {
			    	                {null, null, null},
			    	                {null, null, null},
			    	                {null, null, null},
			    	                {null, null, null}
			    	            },
				    	            new String [] {
				    	                "Nik", "Name", "Password"
				    	            }
    	        ) 
        		);
        loadTable();
        //loadConectedUsers();
        	
       	table.setModel(model);
     
        jScrollPane1.setViewportView(table);

        jLabel2.setText("Total Ussers");

        disconectButton.setText("Disconect?");

        newButton.setText("New User");

        modifyBotton.setText("Modify User");

        deleteButton.setText("Delete User");

        jLabel3.setText("Nik");

        jLabel4.setText("Password");

        

        jLabel5.setText("Name");

        ExitButton.setText("Exit");

        statusBar.setText("Server GUI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(conectedUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addComponent(numberConectLabel)
                            .addComponent(controlLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberButton))
                            .addComponent(disconectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nikField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(passField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newButton)
                            .addComponent(modifyBotton)
                            .addComponent(deleteButton))))
                .addGap(101, 101, 101)
                .addComponent(ExitButton)
                .addGap(53, 53, 53))
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(ExitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberConectLabel)
                            .addComponent(maxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clientNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(controlLabel))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(conectedUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disconectButton))
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(nikField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(newButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifyBotton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton)))
                        .addGap(19, 19, 19)))
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }// </editor-fold>

   

    private void loadConectedUsers() {
		controller.getUserList();
	}



	private void loadTable() {
    	((DefaultTableModel) model).setRowCount(0);
		List<String> list= new ArrayList<String>();
    	try {
			dao.connect();
			list=dao.getUsers();
			dao.disconnect();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		for (int i=0;i<list.size();i++)
		{ System.out.println(list.get(i));
			StringTokenizer sTok= new StringTokenizer(list.get(i),";");
				String nik=sTok.nextToken();
				String name=sTok.nextToken();
				String pass=sTok.nextToken();
				Object [] row = new Object[3];
            row[0] = nik;
            row[1] =name;
            row[2] = pass;
            ((DefaultTableModel) model).addRow( row );
		}
		
	}



	/**
    * @param args the command line arguments
    */
    

	@Override
public void actionPerformed(ActionEvent e) {
        
        if (e.getSource() instanceof JButton)
        {
                JButton buttonPressed=(JButton)e.getSource();
                if (buttonPressed==NumberButton)
                {
                	String number=maxNumber.getText();
                	controller.setMaxNumberConnections(Integer.parseInt(number));
                }
                if (buttonPressed==modifyBotton)
                {   int row=table.getSelectedRow();
                System.out.println(row);
            	
                   String SelectedName=(String)model.getValueAt(row, 1);
                   System.out.println(SelectedName);
               	
                	String name=nameField.getText();
                	String nik=nikField.getText();
                	String pass=passField.getText();
                	try {
								dao.connect();
							if (name!="")
		                		dao.changeUserName(SelectedName,name);
		                	if (nik!="")
		                		{System.out.println("ha entrado");
		                	
		                		dao.changeUserNick(SelectedName,nik);}
		                	if (pass!="")
		                		dao.changeUserPassWord(SelectedName, pass);
		                	statusBar.setText("Correctly change");
		               dao.disconnect(); 
                	} catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
                	loadTable();
                }
                if (buttonPressed==deleteButton)
                {
                	 int row=table.getSelectedRow();
                     String SelectedName=(String)model.getValueAt(row, 1);
                     System.out.println(SelectedName);
                     try {
							dao.connect();
							dao.deleteUser(SelectedName);
							dao.disconnect();
                     } catch (SQLException e1) {
 						// TODO Auto-generated catch block
 						e1.printStackTrace();
 					}
                     loadTable();
				}
                
                if (buttonPressed==newButton)
                {
                	String name=nameField.getText();
                	System.out.println(name);
                	String nik=nikField.getText();
                	System.out.println(nik);
                	
                	String pass=passField.getText();
                	System.out.println(pass);
                	
                	try {
						dao.connect();
						dao.insertUser(name, nik, pass);
	                	dao.disconnect();
					} catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
					loadTable();
                 }
                if (buttonPressed==disconectButton)
                {}
                	
                	
                	}
		
	}

  




	}
	


